//! Atomic split commit logic.
//!
//! Groups staged changes into multiple logical commits, each with its own
//! commit message generated by the LLM.

use std::sync::Arc;

use colored::Colorize;
use serde::{Deserialize, Serialize};

use super::{options::CommitOptions, summarize_lockfile_diffs};
use crate::commands::commit::DiffStatsJson;
use crate::commands::json::{self, JsonOutput};
use crate::config::AppConfig;
use crate::error::{GcopError, Result};
use crate::git::diff::{FileDiff, split_diff_by_file};
use crate::git::{DiffStats, GitOperations};
use crate::llm::{CommitContext, LLMProvider, ScopeInfo};
use crate::ui;

/// A single commit group: files + message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitGroup {
    /// Files belonging to this commit group.
    pub files: Vec<String>,
    /// Commit message for this group.
    pub message: String,
}

/// LLM response wrapper for split commit grouping.
#[derive(Debug, Deserialize)]
struct SplitResponse {
    groups: Vec<CommitGroup>,
}

/// JSON output data for `--split --json` mode.
#[derive(Debug, Serialize)]
pub struct SplitCommitData {
    /// Generated commit groups.
    pub groups: Vec<CommitGroup>,
    /// Overall diff statistics.
    pub diff_stats: DiffStatsJson,
    /// Whether commits were actually executed.
    pub committed: bool,
}

// --- Public entry point ------------------------------------------------------

/// Main entry point for the split commit flow.
///
/// Called from `commands::commit::run_with_deps()` when `options.split` is true.
pub async fn run_split_flow(
    options: &CommitOptions<'_>,
    config: &AppConfig,
    repo: &dyn GitOperations,
    provider: &Arc<dyn LLMProvider>,
) -> Result<()> {
    let colored = options.effective_colored(config);

    let initial_feedbacks = if options.feedback.is_empty() {
        vec![]
    } else {
        vec![options.feedback.join(" ")]
    };

    // JSON mode owns its own history sampling (after its own staged + lockfile gates).
    if options.format.is_json() {
        return handle_split_json_mode(options, config, repo, provider, &initial_feedbacks).await;
    }

    // Check staged changes
    if !repo.has_staged_changes()? {
        ui::error(&rust_i18n::t!("commit.no_staged_changes"), colored);
        return Err(GcopError::NoStagedChanges);
    }

    // Get diff and split by file
    let diff = repo.get_staged_diff()?;
    let stats = repo.get_diff_stats(&diff)?;
    let file_diffs = split_diff_by_file(&diff);
    let (prompt_file_diffs, summarized) =
        summarize_lockfile_diffs(&file_diffs, &config.file.lockfile_patterns);
    if summarized {
        ui::warning(&rust_i18n::t!("diff.truncated"), colored);
    }

    if file_diffs.is_empty() {
        ui::error(&rust_i18n::t!("commit.no_staged_changes"), colored);
        return Err(GcopError::NoStagedChanges);
    }

    // Workspace scope detection
    let scope_info = super::commit::compute_scope_info_pub(&stats.files_changed, config);

    ui::step(
        &rust_i18n::t!("commit.step1"),
        &rust_i18n::t!(
            "commit.analyzed",
            files = stats.files_changed.len(),
            changes = stats.insertions + stats.deletions
        ),
        colored,
    );

    // Lockfile-only shortcut: build a single group with all staged files
    // and commit it directly, skipping the LLM entirely.
    if let Some(msg) = crate::commands::try_lockfile_shortcut(&stats.files_changed, config) {
        let groups = vec![CommitGroup {
            files: stats.files_changed.clone(),
            message: msg,
        }];
        display_commit_groups(&groups, &file_diffs, colored);
        if options.dry_run {
            return Ok(());
        }
        return execute_split_commits(repo, &groups, colored);
    }

    // If only 1 file, no need to split - just inform and suggest normal commit
    if file_diffs.len() == 1 {
        ui::warning(&rust_i18n::t!("split.single_file"), colored);
        // Fall through to generate a single group anyway
    }

    // Sample history AFTER all early-return gates so we don't revwalk on
    // staged-changes errors or lockfile shortcuts. Honour --provider override.
    let effective_provider_name = options
        .provider_override
        .unwrap_or(&config.llm.default_provider);
    let historical_examples = crate::llm::history_sampler::gather_reference_messages(
        repo,
        &config.commit.history,
        config.llm.providers.get(effective_provider_name),
        None,
    );

    let branch_name = repo.get_current_branch()?;
    let custom_prompt = config.commit.custom_prompt.clone();
    let mut feedbacks = initial_feedbacks;
    let max_retries = config.commit.max_retries;
    let mut attempt = 0usize;

    // Outer loop: generation
    loop {
        if attempt >= max_retries {
            ui::warning(
                &rust_i18n::t!("commit.max_retries", count = max_retries),
                colored,
            );
            return Err(GcopError::MaxRetriesExceeded(max_retries));
        }

        // Generate groups
        let mut current_groups = generate_groups(
            provider,
            &prompt_file_diffs,
            &stats,
            config,
            &feedbacks,
            options.verbose,
            &branch_name,
            &custom_prompt,
            &scope_info,
            &historical_examples,
            colored,
            attempt,
        )
        .await?;

        // Display groups
        display_commit_groups(&current_groups, &file_diffs, colored);

        // dry-run mode: just show and exit
        if options.dry_run {
            return Ok(());
        }

        // auto-accept mode
        if options.yes {
            return execute_split_commits(repo, &current_groups, colored);
        }

        // Inner loop: interaction (edit stays here, regenerate breaks to outer)
        loop {
            let action = split_action_menu(colored, attempt)?;
            match action {
                SplitAction::AcceptAll => {
                    return execute_split_commits(repo, &current_groups, colored);
                }
                SplitAction::Edit => {
                    let edited = edit_groups_in_editor(&current_groups, &stats.files_changed)?;
                    if let Some(edited_groups) = edited {
                        current_groups = edited_groups;
                        display_commit_groups(&current_groups, &file_diffs, colored);
                    } else {
                        ui::warning(&rust_i18n::t!("commit.edit_cancelled"), colored);
                    }
                    // Stay in inner loop — user can edit again, accept, or regenerate
                    continue;
                }
                SplitAction::Regenerate => {
                    attempt += 1;
                    break; // break inner → outer loop regenerates
                }
                SplitAction::RegenerateWithFeedback => {
                    let new_feedback = ui::get_retry_feedback(colored)?;
                    if let Some(fb) = new_feedback {
                        feedbacks.push(fb);
                    } else {
                        ui::warning(&rust_i18n::t!("commit.feedback.empty"), colored);
                    }
                    attempt += 1;
                    break; // break inner → outer loop regenerates
                }
                SplitAction::Quit => {
                    ui::warning(&rust_i18n::t!("commit.cancelled"), colored);
                    return Ok(());
                }
            }
        }
    }
}

// --- Group generation --------------------------------------------------------

/// Generate commit groups from staged diffs using the LLM.
#[allow(clippy::too_many_arguments)]
async fn generate_groups(
    provider: &Arc<dyn LLMProvider>,
    file_diffs: &[FileDiff],
    stats: &DiffStats,
    config: &AppConfig,
    feedbacks: &[String],
    verbose: bool,
    branch_name: &Option<String>,
    custom_prompt: &Option<String>,
    scope_info: &Option<ScopeInfo>,
    historical_examples: &[String],
    colored: bool,
    attempt: usize,
) -> Result<Vec<CommitGroup>> {
    let context = CommitContext {
        files_changed: stats.files_changed.clone(),
        insertions: stats.insertions,
        deletions: stats.deletions,
        branch_name: branch_name.clone(),
        custom_prompt: custom_prompt.clone(),
        user_feedback: feedbacks.to_vec(),
        convention: config.commit.convention.clone(),
        scope_info: scope_info.clone(),
        historical_examples: historical_examples.to_vec(),
    };

    // Build split prompt (system + user)
    let (system, user) = crate::llm::prompt::build_split_commit_prompt(
        file_diffs,
        &context,
        context.custom_prompt.as_deref(),
        context.convention.as_ref(),
    );

    // Verbose: show prompt
    if verbose {
        if colored {
            eprintln!(
                "\n{}",
                rust_i18n::t!("commit.verbose.generated_prompt")
                    .cyan()
                    .bold()
            );
            eprintln!("{}", rust_i18n::t!("commit.verbose.system_prompt").cyan());
            eprintln!("{}", system);
            eprintln!("{}", rust_i18n::t!("commit.verbose.user_message").cyan());
            eprintln!("{}", user);
            eprintln!(
                "{}\n",
                rust_i18n::t!("commit.verbose.divider").cyan().bold()
            );
        } else {
            eprintln!("\n{}", rust_i18n::t!("commit.verbose.generated_prompt"));
            eprintln!("{}", rust_i18n::t!("commit.verbose.system_prompt"));
            eprintln!("{}", system);
            eprintln!("{}", rust_i18n::t!("commit.verbose.user_message"));
            eprintln!("{}", user);
            eprintln!("{}\n", rust_i18n::t!("commit.verbose.divider"));
        }
    }

    // Split mode wants the full JSON response intact; the UI does not stream
    // deltas (the response is parsed as JSON). HTTP transport still streams
    // via SSE when supported, so slow models do not trip CDN first-byte
    // timeouts.
    let step_msg = if attempt == 0 {
        rust_i18n::t!("spinner.generating")
    } else {
        rust_i18n::t!("spinner.regenerating")
    };
    ui::step(&rust_i18n::t!("commit.step2"), &step_msg, colored);

    let spinner_msg = rust_i18n::t!("split.generating_groups").to_string();
    let mut spinner = ui::Spinner::new_with_cancel_hint(&spinner_msg, colored);
    spinner.start_time_display();

    // Direct query with pre-built prompts. `supports_streaming()` already
    // accounts for the user-facing `[llm].stream_transport` opt-out.
    let raw_response = if provider.supports_streaming() {
        provider
            .send_prompt_collect(&system, &user, Some(&spinner))
            .await?
    } else {
        provider.send_prompt(&system, &user, Some(&spinner)).await?
    };

    spinner.finish_and_clear();

    // Parse the response. Thread the provider's thinking-tag policy so the
    // plain-text fallback normalises reasoning models' output the same way the
    // single-commit path does. Both the interactive/-y outer loop and
    // handle_split_json_mode reach this chokepoint.
    parse_split_response_with_options(
        &raw_response,
        &stats.files_changed,
        provider.strip_thinking(),
    )
}

// --- Response parsing --------------------------------------------------------

/// Parse the LLM response into commit groups.
///
/// Strips markdown code fences if present, then parses JSON.
/// Validates that every staged file appears exactly once.
///
/// Thin wrapper over [`parse_split_response_with_options`] with
/// `strip_thinking = true` (the safe default; thinking-tag stripping is
/// idempotent on already-clean text). Kept as the public 2-arg signature so
/// existing call sites and tests are unaffected.
pub fn parse_split_response(raw: &str, expected_files: &[String]) -> Result<Vec<CommitGroup>> {
    parse_split_response_with_options(raw, expected_files, true)
}

/// Parse the LLM response into commit groups, honouring the provider's
/// thinking-tag policy for the plain-text fallback path.
///
/// Resolution order when the strict parse fails (requirement: split mode must
/// degrade gracefully instead of hard-failing whenever it safely can):
///
/// 1. Strict parse of the (fence-stripped, BOM-stripped) whole string.
/// 2. RECOVER embedded JSON: if the response wraps a valid `groups` object in
///    a prose preamble, markdown decoration, or an unterminated code fence,
///    slice the outermost `{ … }` span and re-parse it — preserving the
///    model's real atomic grouping.
/// 3. PLAIN-TEXT fallback: if the response is a usable single commit message
///    (and shows NO JSON-attempt signal), treat it as the model collapsing
///    ALL staged changes into ONE atomic commit and synthesise a single group
///    covering every expected file. Mirrors non-split (Base) behaviour.
/// 4. Otherwise preserve the original parse error.
///
/// Crucially, malformed/truncated/structured JSON is NEVER committed verbatim
/// as a message — a structural check (see [`looks_like_json_attempt`],
/// independent of quoting style, key names, and prose/markdown/fence
/// decoration) makes such input error so the caller can retry, exactly as the
/// requirement demands.
pub(crate) fn parse_split_response_with_options(
    raw: &str,
    expected_files: &[String],
    strip_thinking: bool,
) -> Result<Vec<CommitGroup>> {
    // Strip a whole-string markdown fence, then a leading BOM / zero-width
    // prefix so an otherwise-valid JSON body still parses and the broken-JSON
    // guards see the true leading character.
    let json_str = strip_invisible_prefix(strip_code_fences(raw));

    // Parse JSON; on failure try embedded-JSON recovery, then a single-group
    // plain-text fallback.
    let mut response: SplitResponse = match serde_json::from_str(json_str) {
        Ok(resp) => resp,
        Err(e) => {
            // (1) Recover a valid groups object wrapped in prose/markdown/an
            //     unterminated fence — but ONLY when it covers every staged
            //     file. A subset-covering recovery would silently leave the
            //     omitted files uncommitted (the missing-files branch below is
            //     warn-only), so we decline it and fall through to error.
            if let Some(recovered) = recover_embedded_split_response(json_str)
                && covers_all_expected(&recovered, expected_files)
            {
                tracing::warn!(
                    "split: recovered a JSON groups object embedded in a non-JSON wrapper"
                );
                recovered
            } else if let Some(groups) =
                try_single_group_fallback(json_str, expected_files, strip_thinking)
            {
                tracing::warn!(
                    "split: LLM returned non-JSON; treating the whole response as a single \
                     atomic commit covering all staged files"
                );
                SplitResponse { groups }
            } else {
                // Truncate preview at char boundary to avoid panic on multi-byte UTF-8
                let preview: String = raw.chars().take(200).collect();
                return Err(GcopError::SplitParseFailed(format!(
                    "JSON parse error: {}. Response preview: {}",
                    e, preview
                )));
            }
        }
    };

    // Apply deterministic sanitisation to every group message so the split
    // path matches the single-commit path (which already runs sanitise via
    // `process_commit_response_with_options`). This drops forbidden trailers,
    // lowercases the Conventional Commit type, removes trailing periods,
    // and collapses blank-line runs.
    for group in &mut response.groups {
        group.message =
            crate::llm::provider::base::sanitize::sanitize_commit_message(&group.message);
    }

    if response.groups.is_empty() {
        return Err(GcopError::SplitParseFailed(
            "LLM returned empty groups".to_string(),
        ));
    }

    // Validate: collect all files from groups
    let mut seen_files = std::collections::HashSet::new();
    for group in &response.groups {
        if group.files.is_empty() {
            return Err(GcopError::SplitParseFailed(format!(
                "Group '{}' has no files",
                group.message
            )));
        }
        if group.message.trim().is_empty() {
            return Err(GcopError::SplitParseFailed(
                "Group has empty commit message".to_string(),
            ));
        }
        for file in &group.files {
            if !seen_files.insert(file.clone()) {
                return Err(GcopError::SplitParseFailed(format!(
                    "File '{}' appears in multiple groups",
                    file
                )));
            }
        }
    }

    // Check that all expected files are covered
    let expected_set: std::collections::HashSet<_> = expected_files.iter().cloned().collect();
    let missing: Vec<_> = expected_set.difference(&seen_files).collect();
    if !missing.is_empty() {
        // Not a hard error - LLM might use slightly different paths
        // Log warning but proceed
        tracing::warn!("Some staged files not covered by LLM groups: {:?}", missing);
    }

    // Check that LLM did not return files outside the staging area.
    // Staging and committing such files would silently include unstaged working-tree
    // changes that the user never intended to commit.
    let mut extra: Vec<_> = seen_files.difference(&expected_set).cloned().collect();
    if !extra.is_empty() {
        extra.sort();
        return Err(GcopError::SplitParseFailed(format!(
            "LLM returned files not in staging area: {:?}",
            extra
        )));
    }

    Ok(response.groups)
}

/// Strip a leading UTF-8 BOM and common zero-width / format code points so
/// they cannot mask a leading `{`/`[` (or defeat a strict JSON parse).
fn strip_invisible_prefix(s: &str) -> &str {
    s.trim_start_matches([
        '\u{feff}', // BOM / zero-width no-break space
        '\u{200b}', // zero-width space
        '\u{200c}', // zero-width non-joiner
        '\u{200d}', // zero-width joiner
        '\u{2060}', // word joiner
    ])
}

/// Does every expected (staged) file appear in some recovered group?
///
/// A recovery that covers only a subset would silently leave the omitted
/// files uncommitted, so the caller only accepts a fully-covering recovery.
fn covers_all_expected(resp: &SplitResponse, expected_files: &[String]) -> bool {
    let covered: std::collections::HashSet<&str> = resp
        .groups
        .iter()
        .flat_map(|g| g.files.iter())
        .map(String::as_str)
        .collect();
    expected_files.iter().all(|f| covered.contains(f.as_str()))
}

/// Does `s` look like an attempted (possibly malformed/truncated) JSON/
/// structured response rather than a plain commit message?
///
/// The check is STRUCTURAL, not a substring deny-list — so it is independent
/// of quoting style (`{groups:`, `{'groups':`, `{"groups":`), key names
/// (renamed keys like `commit_groups`, dotted/spaced/non-ASCII keys), and any
/// prose/markdown/heading/fence decoration wrapping the structure. Three
/// signals, any sufficient:
///   (a) the candidate (after invisible-prefix + whitespace trim) STARTS WITH
///       a literal `{` — no real commit subject opens with an object brace, so
///       any brace-wrapped object or prose (`{ summary }`, `{commit.groups:1}`,
///       `{"two words": 1}`, `{группы: …}`) is debris regardless of its inner
///       shape; OR
///   (b) a structure opener anywhere: a `{` that begins an object (next
///       meaningful token is a `key:` or a nested `{`/`[`) or a `[` that
///       begins an array of objects/strings; OR
///   (c) an unclosed `{`/`[` opener — a truncated structure (streaming
///       cut-off).
///
/// Plain commit subjects with balanced inline punctuation (`fix: {id} route`,
/// `[skip ci] chore: x`, `rename "message" field {Config}`) do not open with a
/// brace, have no key-colon opener, and stay balanced, so they are NOT
/// misclassified. Such structured text must never be committed verbatim as a
/// message; it errors so the caller retries.
fn looks_like_json_attempt(s: &str) -> bool {
    strip_invisible_prefix(s).trim_start().starts_with('{')
        || has_structure_opener(s)
        || has_unclosed_opener(s)
}

/// Scan for a `{`/`[` that opens a JSON-style object/array (quoting- and
/// key-name-agnostic). All delimiters checked are ASCII, so byte indexing is
/// codepoint-safe.
fn has_structure_opener(s: &str) -> bool {
    let b = s.as_bytes();
    let n = b.len();
    let mut i = 0;
    while i < n {
        match b[i] {
            b'{' => {
                let mut j = i + 1;
                while j < n && b[j].is_ascii_whitespace() {
                    j += 1;
                }
                if j < n {
                    // Nested opener → structure.
                    if b[j] == b'{' || b[j] == b'[' {
                        return true;
                    }
                    // Optional quote, then an identifier, optional closing
                    // quote, whitespace, then ':' → an object key.
                    let mut k = j;
                    let quoted = b[k] == b'"' || b[k] == b'\'';
                    if quoted {
                        k += 1;
                    }
                    let id_start = k;
                    while k < n && (b[k].is_ascii_alphanumeric() || b[k] == b'_' || b[k] == b'-') {
                        k += 1;
                    }
                    if k > id_start {
                        if quoted && k < n && (b[k] == b'"' || b[k] == b'\'') {
                            k += 1;
                        }
                        while k < n && b[k].is_ascii_whitespace() {
                            k += 1;
                        }
                        if k < n && b[k] == b':' {
                            return true;
                        }
                    }
                }
            }
            b'[' => {
                let mut j = i + 1;
                while j < n && b[j].is_ascii_whitespace() {
                    j += 1;
                }
                // Array of objects/arrays/strings → structure. A bracketed
                // word tag like "[skip ci]" is NOT (next token is a bareword).
                if j < n && matches!(b[j], b'{' | b'[' | b'"' | b'\'') {
                    return true;
                }
            }
            _ => {}
        }
        i += 1;
    }
    false
}

/// Are there unclosed `{`/`[` openers? Strong tell of a truncated structure
/// (a streaming cut-off loses the trailing closers, leaving EXCESS OPENERS).
///
/// Only excess openers count — never excess closers — so a plain commit
/// message that merely mentions a stray closing brace ("fix: drop trailing }"
/// ) is not misclassified, while every truncated JSON fragment is still
/// caught. Counts all braces (including any inside strings); the
/// structure-opener check handles fully-balanced structures.
fn has_unclosed_opener(s: &str) -> bool {
    let mut curly: i32 = 0;
    let mut square: i32 = 0;
    for c in s.bytes() {
        match c {
            b'{' => curly += 1,
            b'}' => curly = (curly - 1).max(0),
            b'[' => square += 1,
            b']' => square = (square - 1).max(0),
            _ => {}
        }
    }
    curly > 0 || square > 0
}

/// Recover a `groups` object embedded in a non-JSON wrapper (prose preamble,
/// markdown decoration, or an unterminated fence). Tries each `{` as an object
/// start, finds its brace-balanced end (skipping braces inside JSON string
/// literals), and re-parses that span as the strict split schema; returns the
/// first that parses. Returns `None` when no balanced object parses — so
/// truncated JSON (no matching `}`) is NOT recovered and falls through to the
/// error path rather than being committed. Wrapper prose that contains its own
/// braces (`use {placeholder} then: {…json…}`) no longer defeats extraction.
fn recover_embedded_split_response(s: &str) -> Option<SplitResponse> {
    let b = s.as_bytes();
    let n = b.len();
    let mut i = 0;
    while i < n {
        if b[i] == b'{'
            && let Some(end) = matching_brace_end(b, i)
            && let Ok(resp) = serde_json::from_str::<SplitResponse>(&s[i..=end])
        {
            return Some(resp);
        }
        i += 1;
    }
    None
}

/// Byte index of the `}` that closes the `{` at `open`, tracking nesting and
/// ignoring braces inside double-quoted JSON strings (with `\` escapes).
/// `None` if unbalanced. All matched bytes are ASCII → slice boundaries stay
/// codepoint-safe.
fn matching_brace_end(b: &[u8], open: usize) -> Option<usize> {
    let mut depth: usize = 0;
    let mut in_str = false;
    let mut escaped = false;
    let mut i = open;
    while i < b.len() {
        let c = b[i];
        if in_str {
            if escaped {
                escaped = false;
            } else if c == b'\\' {
                escaped = true;
            } else if c == b'"' {
                in_str = false;
            }
        } else {
            match c {
                b'"' => in_str = true,
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(i);
                    }
                }
                _ => {}
            }
        }
        i += 1;
    }
    None
}

/// Attempt to recover a single-group commit from a non-JSON LLM response.
///
/// Returns `Some(vec![group])` when the text reads as a usable commit
/// message, where the group covers EVERY expected (staged) file — i.e. the
/// model is interpreted as having collapsed all changes into one atomic
/// commit, which is exactly Base (non-split) behaviour. Returns `None` (so
/// the caller keeps the original parse error) when:
///   - nothing is staged (`expected_files` empty) — never synthesise a commit;
///   - the text looks like a JSON attempt (see [`looks_like_json_attempt`]) —
///     malformed/truncated JSON, or JSON-in-prose, must error not commit;
///   - the text normalises to empty (e.g. it was only a forbidden trailer or
///     an AI-attribution banner that the sanitiser strips away).
///
/// The candidate is normalised through the SAME pipeline Base mode uses
/// (`process_commit_response_with_options`: strip thinking tags → strip a
/// whole-string fence → deterministic sanitise), so a fallback commit message
/// is byte-for-byte what the single-commit path would have produced.
fn try_single_group_fallback(
    json_str: &str,
    expected_files: &[String],
    strip_thinking: bool,
) -> Option<Vec<CommitGroup>> {
    // Never fabricate a commit when nothing is staged.
    if expected_files.is_empty() {
        return None;
    }

    // Broken/truncated/embedded JSON is not a commit message. (Recovery of a
    // *valid* embedded object already ran in the caller; reaching here with a
    // JSON signal means it was malformed — error, do not commit it verbatim.)
    if looks_like_json_attempt(json_str) {
        return None;
    }

    // Normalise to Base-mode parity.
    let message = crate::llm::provider::base::process_commit_response_with_options(
        json_str.to_string(),
        strip_thinking,
    );
    if message.trim().is_empty() {
        return None;
    }

    Some(vec![CommitGroup {
        files: expected_files.to_vec(),
        message,
    }])
}

/// Strip markdown code fences from a string.
fn strip_code_fences(s: &str) -> &str {
    let trimmed = s.trim();

    // Try ```json ... ``` pattern
    if let Some(rest) = trimmed.strip_prefix("```json")
        && let Some(inner) = rest.strip_suffix("```")
    {
        return inner.trim();
    }

    // Try ``` ... ``` pattern
    if let Some(rest) = trimmed.strip_prefix("```")
        && let Some(inner) = rest.strip_suffix("```")
    {
        return inner.trim();
    }

    trimmed
}

// --- Commit execution --------------------------------------------------------

/// Execute split commits sequentially with error recovery.
fn execute_split_commits(
    repo: &dyn GitOperations,
    groups: &[CommitGroup],
    colored: bool,
) -> Result<()> {
    let total = groups.len();

    ui::step(
        &rust_i18n::t!("commit.step4"),
        &rust_i18n::t!("split.committing", total = total),
        colored,
    );

    // Step 1: Unstage all files
    repo.unstage_all()?;

    // Step 2: Commit each group
    for (i, group) in groups.iter().enumerate() {
        // Stage this group's files
        repo.stage_files(&group.files)?;

        // Commit
        match repo.commit(&group.message) {
            Ok(()) => {
                if colored {
                    println!(
                        "  {} {}/{}: {}",
                        "✓".green().bold(),
                        i + 1,
                        total,
                        group.message.yellow()
                    );
                } else {
                    println!("  ✓ {}/{}: {}", i + 1, total, group.message);
                }
            }
            Err(e) => {
                // Recovery: re-stage remaining files
                let remaining_files: Vec<String> =
                    groups[i..].iter().flat_map(|g| g.files.clone()).collect();

                // Try to recover staging state
                let _ = repo.unstage_all();
                let _ = repo.stage_files(&remaining_files);

                return Err(GcopError::SplitCommitPartial {
                    completed: i,
                    total,
                    detail: e.to_string(),
                });
            }
        }
    }

    println!();
    ui::success(&rust_i18n::t!("split.success", count = total), colored);
    Ok(())
}

// --- Display -----------------------------------------------------------------

/// Display commit groups in a formatted preview.
fn display_commit_groups(groups: &[CommitGroup], file_diffs: &[FileDiff], colored: bool) {
    let total = groups.len();

    ui::step(
        &rust_i18n::t!("commit.step2"),
        &rust_i18n::t!("split.generated_groups", count = total),
        colored,
    );
    println!();

    for (i, group) in groups.iter().enumerate() {
        if colored {
            println!(
                "  {} ({} {}):",
                format!("Group {}", i + 1).cyan().bold(),
                group.files.len(),
                if group.files.len() == 1 {
                    "file"
                } else {
                    "files"
                }
            );
            println!("    {}", group.message.yellow());
        } else {
            println!(
                "  Group {} ({} {}):",
                i + 1,
                group.files.len(),
                if group.files.len() == 1 {
                    "file"
                } else {
                    "files"
                }
            );
            println!("    {}", group.message);
        }

        for file in &group.files {
            // Find diff stats for this file
            let (ins, del) = file_diffs
                .iter()
                .find(|fd| fd.filename == *file)
                .map(|fd| (fd.insertions, fd.deletions))
                .unwrap_or((0, 0));

            if colored {
                println!("    {} {} (+{} -{})", "-".dimmed(), file, ins, del);
            } else {
                println!("    - {} (+{} -{})", file, ins, del);
            }
        }
        println!();
    }
}

// --- Interactive menu --------------------------------------------------------

/// User action choices for split commit mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SplitAction {
    AcceptAll,
    Edit,
    Regenerate,
    RegenerateWithFeedback,
    Quit,
}

/// Show the split commit action menu.
fn split_action_menu(colored: bool, retry_count: usize) -> Result<SplitAction> {
    use inquire::InquireError;
    use rust_i18n::t;

    let mut options = Vec::new();

    if colored {
        options.push(format!(
            "{} {}",
            "✓".green().bold(),
            t!("split.menu.accept_all").green()
        ));
        options.push(format!(
            "{} {}",
            "✎".yellow().bold(),
            t!("split.menu.edit").yellow()
        ));
        options.push(format!(
            "{} {}",
            "↻".blue().bold(),
            t!("split.menu.regenerate").blue()
        ));
        options.push(format!(
            "{} {}",
            "↻+".blue().bold(),
            t!("split.menu.regenerate_feedback").blue()
        ));
        options.push(format!(
            "{} {}",
            "✕".red().bold(),
            t!("split.menu.quit").red()
        ));
    } else {
        options.push(format!("✓ {}", t!("split.menu.accept_all")));
        options.push(format!("✎ {}", t!("split.menu.edit")));
        options.push(format!("↻ {}", t!("split.menu.regenerate")));
        options.push(format!("↻+ {}", t!("split.menu.regenerate_feedback")));
        options.push(format!("✕ {}", t!("split.menu.quit")));
    }

    let prompt = if colored {
        if retry_count == 0 {
            format!(
                "{} {}",
                t!("split.menu.choose_action").cyan().bold(),
                t!("messages.esc_to_quit").dimmed()
            )
        } else {
            format!(
                "{} {}",
                t!("commit.menu.not_satisfied").cyan().bold(),
                t!("messages.esc_to_quit").dimmed()
            )
        }
    } else if retry_count == 0 {
        format!(
            "{} {}",
            t!("split.menu.choose_action"),
            t!("messages.esc_to_quit")
        )
    } else {
        format!(
            "{} {}",
            t!("commit.menu.not_satisfied"),
            t!("messages.esc_to_quit")
        )
    };

    let selection = match inquire::Select::new(&prompt, options)
        .with_starting_cursor(0)
        .raw_prompt()
    {
        Ok(choice) => choice.index,
        Err(InquireError::OperationCanceled | InquireError::OperationInterrupted) => {
            return Ok(SplitAction::Quit);
        }
        Err(_) => return Err(GcopError::UserCancelled),
    };

    Ok(match selection {
        0 => SplitAction::AcceptAll,
        1 => SplitAction::Edit,
        2 => SplitAction::Regenerate,
        3 => SplitAction::RegenerateWithFeedback,
        _ => SplitAction::Quit,
    })
}

// --- Editor support ----------------------------------------------------------

/// TOML wrapper for editor serialization/deserialization.
#[derive(Debug, Serialize, Deserialize)]
struct EditorGroups {
    groups: Vec<CommitGroup>,
}

/// Format groups as TOML for editor editing.
fn format_groups_for_editor(groups: &[CommitGroup]) -> String {
    let header = "# Atomic Commit Groups\n\
                  # Edit messages, move files between groups, or delete groups.\n\
                  # Empty groups (no files) will be skipped.\n\n";

    let wrapper = EditorGroups {
        groups: groups.to_vec(),
    };
    let toml_body = toml::to_string_pretty(&wrapper).unwrap_or_default();

    // Insert "# Group N" comments before each [[groups]] for readability
    let mut count = 0usize;
    let toml_body = toml_body
        .lines()
        .map(|line| {
            if line.trim() == "[[groups]]" {
                count += 1;
                format!("# Group {}\n{}", count, line)
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!("{}{}\n", header, toml_body)
}

/// Parse groups from TOML editor output.
fn parse_groups_from_editor(text: &str, expected_files: &[String]) -> Result<Vec<CommitGroup>> {
    let editor_groups: EditorGroups = toml::from_str(text)
        .map_err(|e| GcopError::SplitParseFailed(format!("TOML parse error: {}", e)))?;

    // Filter out empty groups (no files or empty message)
    let groups: Vec<CommitGroup> = editor_groups
        .groups
        .into_iter()
        .filter(|g| !g.files.is_empty() && !g.message.trim().is_empty())
        .map(|mut g| {
            // Trim trailing whitespace from message
            g.message = g.message.trim().to_string();
            g
        })
        .collect();

    if groups.is_empty() {
        return Err(GcopError::SplitParseFailed(
            "No valid groups found in editor output".to_string(),
        ));
    }

    // Validate: no duplicate files
    let mut seen = std::collections::HashSet::new();
    for group in &groups {
        for file in &group.files {
            if !seen.insert(file.clone()) {
                return Err(GcopError::SplitParseFailed(format!(
                    "File '{}' appears in multiple groups",
                    file
                )));
            }
        }
    }

    // Warn about missing files
    let expected_set: std::collections::HashSet<_> = expected_files.iter().cloned().collect();
    let missing: Vec<_> = expected_set.difference(&seen).collect();
    if !missing.is_empty() {
        tracing::warn!("Files removed from groups: {:?}", missing);
    }

    Ok(groups)
}

/// Open groups in editor for editing.
fn edit_groups_in_editor(
    groups: &[CommitGroup],
    expected_files: &[String],
) -> Result<Option<Vec<CommitGroup>>> {
    let content = format_groups_for_editor(groups);

    match ui::edit_text(&content) {
        Ok(edited) => {
            let parsed = parse_groups_from_editor(&edited, expected_files)?;
            Ok(Some(parsed))
        }
        Err(GcopError::UserCancelled) => Ok(None),
        Err(e) => Err(e),
    }
}

// --- JSON mode ---------------------------------------------------------------

/// Handle `--split --json` mode.
async fn handle_split_json_mode(
    options: &CommitOptions<'_>,
    config: &AppConfig,
    repo: &dyn GitOperations,
    provider: &Arc<dyn LLMProvider>,
    initial_feedbacks: &[String],
) -> Result<()> {
    if !repo.has_staged_changes()? {
        json::output_json_error::<SplitCommitData>(&GcopError::NoStagedChanges)?;
        return Err(GcopError::NoStagedChanges);
    }

    let diff = repo.get_staged_diff()?;
    let stats = repo.get_diff_stats(&diff)?;
    let file_diffs = split_diff_by_file(&diff);

    // Lockfile-only shortcut for `--split --json`: emit a single-group
    // payload with `committed: false`, matching the JSON mode contract.
    if let Some(msg) = crate::commands::try_lockfile_shortcut(&stats.files_changed, config) {
        let groups = vec![CommitGroup {
            files: stats.files_changed.clone(),
            message: msg,
        }];
        let output = JsonOutput {
            success: true,
            data: Some(SplitCommitData {
                groups,
                diff_stats: (&stats).into(),
                committed: false,
            }),
            error: None,
        };
        println!("{}", serde_json::to_string_pretty(&output)?);
        return Ok(());
    }

    let (prompt_file_diffs, _) =
        summarize_lockfile_diffs(&file_diffs, &config.file.lockfile_patterns);
    let branch_name = repo.get_current_branch()?;
    let custom_prompt = config.commit.custom_prompt.clone();
    let scope_info = super::commit::compute_scope_info_pub(&stats.files_changed, config);

    // Sample history AFTER all early-return gates. Honour --provider override.
    let effective_provider_name = options
        .provider_override
        .unwrap_or(&config.llm.default_provider);
    let historical_examples = crate::llm::history_sampler::gather_reference_messages(
        repo,
        &config.commit.history,
        config.llm.providers.get(effective_provider_name),
        None,
    );

    match generate_groups(
        provider,
        &prompt_file_diffs,
        &stats,
        config,
        initial_feedbacks,
        options.verbose,
        &branch_name,
        &custom_prompt,
        &scope_info,
        &historical_examples,
        false,
        0,
    )
    .await
    {
        Ok(groups) => {
            let output = JsonOutput {
                success: true,
                data: Some(SplitCommitData {
                    groups,
                    diff_stats: (&stats).into(),
                    committed: false,
                }),
                error: None,
            };
            println!("{}", serde_json::to_string_pretty(&output)?);
            Ok(())
        }
        Err(e) => {
            json::output_json_error::<SplitCommitData>(&e)?;
            Err(e)
        }
    }
}

// --- Tests -------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strip_code_fences_json() {
        let input = "```json\n{\"groups\": []}\n```";
        assert_eq!(strip_code_fences(input), "{\"groups\": []}");
    }

    #[test]
    fn test_strip_code_fences_plain() {
        let input = "```\n{\"groups\": []}\n```";
        assert_eq!(strip_code_fences(input), "{\"groups\": []}");
    }

    #[test]
    fn test_strip_code_fences_none() {
        let input = "{\"groups\": []}";
        assert_eq!(strip_code_fences(input), "{\"groups\": []}");
    }

    #[test]
    fn test_parse_split_response_valid() {
        let raw = r#"{"groups": [{"files": ["a.rs", "b.rs"], "message": "feat: add stuff"}]}"#;
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].files, vec!["a.rs", "b.rs"]);
        assert_eq!(groups[0].message, "feat: add stuff");
    }

    #[test]
    fn test_parse_split_response_with_fences() {
        let raw =
            "```json\n{\"groups\": [{\"files\": [\"a.rs\"], \"message\": \"fix: bug\"}]}\n```";
        let expected = vec!["a.rs".to_string()];
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 1);
    }

    #[test]
    fn test_parse_split_response_empty_groups() {
        let raw = r#"{"groups": []}"#;
        let result = parse_split_response(raw, &[]);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_split_response_duplicate_file() {
        let raw = r#"{"groups": [
            {"files": ["a.rs"], "message": "feat: one"},
            {"files": ["a.rs"], "message": "feat: two"}
        ]}"#;
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response(raw, &expected);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("multiple groups"));
    }

    #[test]
    fn test_parse_split_response_empty_message() {
        let raw = r#"{"groups": [{"files": ["a.rs"], "message": ""}]}"#;
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response(raw, &expected);
        assert!(result.is_err());
    }

    #[test]
    fn test_format_and_parse_editor_roundtrip() {
        let groups = vec![
            CommitGroup {
                files: vec!["src/main.rs".to_string(), "src/lib.rs".to_string()],
                message: "feat: add new feature".to_string(),
            },
            CommitGroup {
                files: vec!["tests/test.rs".to_string()],
                message: "test: add tests".to_string(),
            },
        ];

        let editor_text = format_groups_for_editor(&groups);
        let expected_files = vec![
            "src/main.rs".to_string(),
            "src/lib.rs".to_string(),
            "tests/test.rs".to_string(),
        ];
        let parsed = parse_groups_from_editor(&editor_text, &expected_files).unwrap();

        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].message, "feat: add new feature");
        assert_eq!(parsed[0].files, vec!["src/main.rs", "src/lib.rs"]);
        assert_eq!(parsed[1].message, "test: add tests");
        assert_eq!(parsed[1].files, vec!["tests/test.rs"]);
    }

    #[test]
    fn test_format_and_parse_editor_multiline_message() {
        let groups = vec![CommitGroup {
            files: vec!["src/auth.rs".to_string()],
            message: "feat(auth): add login\n\nDetailed description.\n- bullet point".to_string(),
        }];

        let editor_text = format_groups_for_editor(&groups);
        assert!(editor_text.contains("\"\"\""));

        let expected_files = vec!["src/auth.rs".to_string()];
        let parsed = parse_groups_from_editor(&editor_text, &expected_files).unwrap();

        assert_eq!(parsed.len(), 1);
        assert_eq!(
            parsed[0].message,
            "feat(auth): add login\n\nDetailed description.\n- bullet point"
        );
    }

    #[test]
    fn test_parse_split_response_extra_files_rejected() {
        // LLM returns a file that was never staged — must be a hard error
        let raw = r#"{"groups": [
            {"files": ["a.rs", "unstaged.rs"], "message": "feat: one"}
        ]}"#;
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response(raw, &expected);
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("not in staging area"),
            "error should mention staging area, got: {msg}"
        );
    }

    #[test]
    fn test_parse_split_response_extra_files_across_groups_rejected() {
        // Extra file spread across multiple groups — still rejected
        let raw = r#"{"groups": [
            {"files": ["a.rs"], "message": "feat: one"},
            {"files": ["b.rs", "surprise.rs"], "message": "feat: two"}
        ]}"#;
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        let result = parse_split_response(raw, &expected);
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("not in staging area")
        );
    }

    #[test]
    fn test_parse_split_response_no_extra_files_ok() {
        // Exact match — should pass
        let raw = r#"{"groups": [
            {"files": ["a.rs"], "message": "feat: one"},
            {"files": ["b.rs"], "message": "feat: two"}
        ]}"#;
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        assert!(parse_split_response(raw, &expected).is_ok());
    }

    // === Plain-text fallback (LLM ignored the JSON split contract) ===========
    //
    // When JSON parsing fails but the response is a usable commit message, the
    // model is treated as having collapsed all staged changes into one atomic
    // commit: a single group covering EVERY expected file. Broken/truncated
    // JSON (leading `{`/`[`) and empty/blank responses keep the parse error.

    #[test]
    fn parse_fallback_bare_conventional_subject_single_group() {
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        let groups = parse_split_response("feat: add retry logic", &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].files, expected);
        assert_eq!(groups[0].message, "feat: add retry logic");
    }

    #[test]
    fn parse_fallback_fenced_plaintext_message() {
        let expected = vec!["x.rs".to_string()];
        let groups =
            parse_split_response("```\nfix(parser): handle empty input\n```", &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "fix(parser): handle empty input");
        assert_eq!(groups[0].files, expected);
    }

    #[test]
    fn parse_fallback_message_with_braces_not_leading() {
        // Only the LEADING char is gated; an inner `{` is fine.
        let expected = vec!["r.rs".to_string()];
        let groups = parse_split_response("fix(api): handle {id} route", &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "fix(api): handle {id} route");
    }

    #[test]
    fn parse_fallback_strips_thinking_tags() {
        // strip_thinking=true via the 2-arg wrapper.
        let expected = vec!["c.rs".to_string()];
        let groups = parse_split_response(
            "<think>weighing options</think>\nchore: bump deps",
            &expected,
        )
        .unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "chore: bump deps");
    }

    #[test]
    fn parse_fallback_drops_forbidden_trailer_keeps_subject() {
        let expected = vec!["f.rs".to_string()];
        let groups =
            parse_split_response("feat: x\n\nCo-authored-by: Bot <b@b>", &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert!(groups[0].message.starts_with("feat: x"));
        assert!(!groups[0].message.contains("Co-authored-by"));
    }

    #[test]
    fn parse_fallback_message_with_body_preserved() {
        let expected = vec!["m.rs".to_string()];
        let groups = parse_split_response(
            "refactor(core): extract helper\n\nMove parsing into its own fn.",
            &expected,
        )
        .unwrap();
        assert_eq!(groups.len(), 1);
        assert!(groups[0].message.contains("refactor(core): extract helper"));
        assert!(groups[0].message.contains("Move parsing into its own fn."));
    }

    #[test]
    fn parse_fallback_non_conventional_subject_accepted() {
        // Base-mode equivalence: a non-Conventional but non-empty, non-brace
        // subject is committed, not rejected.
        let expected = vec!["a.rs".to_string()];
        let groups = parse_split_response("update build script and docs", &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "update build script and docs");
    }

    #[test]
    fn parse_truncated_json_object_keeps_split_parse_failed() {
        let expected = vec!["a.rs".to_string()];
        let err = parse_split_response("{\"groups\": [", &expected).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("JSON parse error"));
        assert!(msg.contains("Response preview"));
    }

    #[test]
    fn parse_truncated_json_array_keeps_split_parse_failed() {
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("[{\"files\":", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_fenced_truncated_json_keeps_split_parse_failed() {
        // After strip_code_fences the text still leads with `{` (unbalanced
        // fenced JSON), so the broken-JSON guard fires.
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("```json\n{\"groups\": [\n```", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_empty_and_whitespace_keep_split_parse_failed() {
        let expected = vec!["a.rs".to_string()];
        assert!(matches!(
            parse_split_response("", &expected),
            Err(GcopError::SplitParseFailed(_))
        ));
        assert!(matches!(
            parse_split_response("   \n  ", &expected),
            Err(GcopError::SplitParseFailed(_))
        ));
    }

    #[test]
    fn parse_only_forbidden_trailer_normalizes_empty_keeps_failed() {
        // The candidate sanitises to empty (no subject survives) → decline.
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("Co-authored-by: Bot <b@b>", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_ai_banner_only_normalizes_empty_keeps_failed() {
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("🤖 Generated with Claude", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_fallback_skipped_when_expected_files_empty() {
        // Nothing staged → never synthesise a commit, even for a valid message.
        let result = parse_split_response("feat: x", &[]);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_fallback_message_matches_base_pipeline() {
        // The fallback message is byte-for-byte what the single-commit (Base)
        // path would have produced from the same raw response.
        let raw = "Feat: Add X.\n\n🤖 Generated with Claude";
        let expected = vec!["f.rs".to_string()];
        let base =
            crate::llm::provider::base::process_commit_response_with_options(raw.to_string(), true);
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups[0].message, base);
        assert_eq!(groups[0].message, "feat: Add X");
    }

    // === JSON wrapped in prose / markdown / unterminated fence ==============
    //
    // A first-char-only guard would let JSON-bearing text be committed
    // verbatim as a garbage message. Instead: recover a VALID embedded object
    // into the real grouping, and DECLINE (keep the parse error) for any
    // malformed/truncated JSON so the caller retries — never commit it.

    #[test]
    fn parse_recovers_prose_prefixed_valid_json() {
        let raw = "Here is the result:\n{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"},{\"files\":[\"b.rs\"],\"message\":\"fix: b\"}]}";
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(
            groups.len(),
            2,
            "the real grouping is recovered, not collapsed"
        );
        assert_eq!(groups[0].files, vec!["a.rs"]);
        assert_eq!(groups[0].message, "feat: a");
        assert_eq!(groups[1].files, vec!["b.rs"]);
    }

    #[test]
    fn parse_recovers_unclosed_fence_valid_json() {
        // No closing fence; strip_code_fences leaves it, but brace extraction
        // still recovers the object.
        let raw = "```json\n{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"}]}";
        let expected = vec!["a.rs".to_string()];
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "feat: a");
    }

    #[test]
    fn parse_recovers_json_with_trailing_prose() {
        let raw =
            "{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"}]}\n\nHope this helps!";
        let expected = vec!["a.rs".to_string()];
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "feat: a");
    }

    #[test]
    fn parse_bom_prefixed_valid_json_parses() {
        let raw = "\u{feff}{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"}]}";
        let expected = vec!["a.rs".to_string()];
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "feat: a");
    }

    #[test]
    fn parse_prose_prefixed_truncated_json_declined() {
        // Truncated JSON behind prose is NOT a commit message.
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("Here is the result:\n{\"groups\": [", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_unclosed_fence_truncated_json_declined() {
        // The exact streaming-cutoff case: ```json opener + truncated body,
        // no closing fence. Must error, never commit the blob.
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("```json\n{\"groups\": [", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_markdown_decorated_truncated_json_declined() {
        let expected = vec!["a.rs".to_string()];
        for raw in [
            "- {\"files\": [",
            "* {\"groups\": [",
            "> {\"groups\": [",
            "1. {\"groups\": [",
        ] {
            assert!(
                matches!(
                    parse_split_response(raw, &expected),
                    Err(GcopError::SplitParseFailed(_))
                ),
                "markdown-decorated truncated JSON must be declined: {raw:?}"
            );
        }
    }

    #[test]
    fn parse_bom_prefixed_truncated_json_declined() {
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("\u{feff}{\"groups\": [", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_wrong_shape_json_object_declined() {
        // Valid JSON, wrong schema (no "groups") — must not be committed.
        let expected = vec!["a.rs".to_string()];
        let result = parse_split_response("{\"foo\":\"bar\"}", &expected);
        assert!(matches!(result, Err(GcopError::SplitParseFailed(_))));
    }

    #[test]
    fn parse_message_mentioning_groups_word_still_accepted() {
        // A genuine plain subject that merely mentions the word "groups"
        // (no brace, no quoted schema key) must NOT be misclassified as JSON.
        let expected = vec!["a.rs".to_string()];
        let groups = parse_split_response("refactor: rename groups to cohorts", &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "refactor: rename groups to cohorts");
    }

    // === Structural JSON-attempt gate (quoting/key-name/decoration agnostic) =
    //
    // The gate is structural, not a substring deny-list: it must DECLINE
    // structured/truncated JSON regardless of quoting style, key names, or
    // prose/markdown/heading/fence decoration — while still ACCEPTING genuine
    // plain commit subjects that merely contain balanced inline punctuation.

    #[test]
    fn parse_declines_structured_json_debris_all_decorations() {
        let expected = vec!["a.rs".to_string()];
        let debris = [
            // stacked markers + truncated, no quoted schema key
            "> > {\"x\": 1",
            "- - {commits: [",
            "> - {'groups': [",
            // prose preamble + unquoted keys (truncated)
            "Here is the JSON:\n{groups: [{files: [a.rs]",
            // prose preamble + single-quoted, FULLY BALANCED (caught structurally)
            "Output:\n{'groups': [{'files': ['a.rs'], 'message': 'feat: a'}]}",
            // prose line, then marker, then truncated brace
            "Note:\n- {oops broken json blob here",
            // fence opener + stacked markers + truncated
            "```json\n- - {truncated",
            // heading + renamed quoted keys (truncated)
            "## Commits\n{\"commit_groups\": [{\"paths\": [\"a.rs\"]",
            // valid JSON, wrong schema
            "{\"foo\":\"bar\"}",
            // bare truncated object behind prose
            "Sure thing:\n{",
        ];
        for raw in debris {
            assert!(
                matches!(
                    parse_split_response(raw, &expected),
                    Err(GcopError::SplitParseFailed(_))
                ),
                "structured/truncated JSON must be declined, not committed: {raw:?}"
            );
        }
    }

    #[test]
    fn parse_declines_brace_wrapped_object_or_prose() {
        // Balanced objects whose first key is dotted / spaced / quoted-multi-
        // word / non-ASCII defeat the key-colon scan, and brace-wrapped prose
        // has no key at all — but NONE of these is a commit subject, and a
        // real subject never opens with a literal `{`. The leading-`{` signal
        // declines them all.
        let expected = vec!["a.rs".to_string()];
        for raw in [
            "{commit.groups: 1}",                     // dotted bareword key
            "{\"my key\": 1}",                        // quoted multi-word key
            "{группы: [a.rs]}",                       // non-ASCII bareword key
            "{\"группы\": [1]}",                      // non-ASCII quoted key
            "{ summary }",                            // brace-wrapped single word
            "{Note to self: split into auth and ui}", // brace-wrapped prose
            "{commit message here}",                  // brace-wrapped prose
            "  \u{feff}{groups: [",                   // BOM + whitespace then object
        ] {
            assert!(
                matches!(
                    parse_split_response(raw, &expected),
                    Err(GcopError::SplitParseFailed(_))
                ),
                "brace-opening debris must be declined, not committed: {raw:?}"
            );
        }
    }

    #[test]
    fn parse_accepts_plain_subjects_with_inline_punctuation() {
        // None of these are structured JSON; all must degrade to a single
        // commit, not hard-error.
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        for raw in [
            "[skip ci] chore: bump deps",
            "[WIP] feat: add parser",
            "fix(api): handle {id} route",
            "refactor(core): rename the \"message\" field\n\nAlso touches {Config} struct",
            "build(deps): bump foo from {1.0} to {2.0}",
            // stray CLOSING brace/bracket is not a truncated opener
            "fix(lexer): drop the trailing } in templates",
            "fix(parser): tolerate a stray ] in input",
        ] {
            let groups = parse_split_response(raw, &expected)
                .unwrap_or_else(|e| panic!("plain subject must be accepted: {raw:?} got {e}"));
            assert_eq!(groups.len(), 1, "single collapsed group for {raw:?}");
            assert_eq!(groups[0].files, expected);
        }
    }

    #[test]
    fn parse_recovery_requires_full_file_coverage() {
        // Valid embedded JSON that covers only a SUBSET of staged files must
        // NOT be silently accepted (it would drop the uncovered file); it
        // declines and, being structural, errors so the caller retries.
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        let raw = "Here:\n{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"}]}";
        assert!(matches!(
            parse_split_response(raw, &expected),
            Err(GcopError::SplitParseFailed(_))
        ));
    }

    #[test]
    fn parse_recovery_ignores_braces_in_wrapper_prose() {
        // A `{placeholder}` in the wrapper must not defeat brace-balanced
        // extraction of the real groups object that follows.
        let expected = vec!["a.rs".to_string()];
        let raw = "Use {placeholder} then:\n{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"}]}";
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 1);
        assert_eq!(groups[0].message, "feat: a");
        assert_eq!(groups[0].files, vec!["a.rs"]);
    }

    #[test]
    fn parse_recovery_covering_all_files_accepted() {
        let expected = vec!["a.rs".to_string(), "b.rs".to_string()];
        let raw = "Done:\n{\"groups\":[{\"files\":[\"a.rs\"],\"message\":\"feat: a\"},{\"files\":[\"b.rs\"],\"message\":\"fix: b\"}]}";
        let groups = parse_split_response(raw, &expected).unwrap();
        assert_eq!(groups.len(), 2);
        assert_eq!(groups[1].message, "fix: b");
    }
}
