//! Commit message sanitisation.
//!
//! Post-processing pipeline applied to LLM-generated commit messages after
//! [`crate::llm::provider::base::response::clean_commit_response`]. Enforces
//! deterministic, mechanical rules that LLMs miss often enough to be worth
//! handling in code instead of the prompt:
//!
//! 1. Drop forbidden trailer lines (`Co-authored-by:`, `Signed-off-by:`,
//!    `Generated-by:`, `Change-Id:`, AI-attribution banners, …) added by
//!    chain-of-thought leakage or training-set habits. Real Conventional
//!    Commits footers (`Closes`, `Fixes`, `Refs`, `BREAKING CHANGE`) are
//!    preserved.
//! 2. Lowercase the Conventional Commit type prefix on the subject line
//!    (`Feat(api): …` → `feat(api): …`). Type is only normalised when it
//!    is in the whitelist; non-conventional headers pass through untouched.
//! 3. Strip a single trailing period from the subject line. Ellipses
//!    (`...` and `…`) are preserved.
//! 4. Collapse runs of ≥ 2 blank lines down to one, except inside fenced
//!    code blocks (where blank lines may be semantic).
//! 5. Trim blank lines from the very top and very bottom of the message.
//!
//! All transformations are pure-string, regex-free, allocation-friendly —
//! consistent with [`crate::llm::provider::base::response`].

/// Conventional Commits type whitelist used by
/// [`normalize_header_type_case`]. Only headers whose type segment
/// case-folds into one of these get their type lowercased.
const COMMIT_TYPES: &[&str] = &[
    "feat", "fix", "docs", "style", "refactor", "perf", "test", "chore", "build", "ci", "revert",
];

/// Trailer keys (case-insensitive) that must always be dropped from the
/// tail trailer block.
const FORBIDDEN_TRAILER_KEYS: &[&str] = &[
    "co-authored-by",
    "signed-off-by",
    "generated-by",
    "generated-with",
    "reviewed-by",
    "authored-by",
    "tested-by",
    "acked-by",
    "suggested-by",
    "assisted-by",
    "helped-by",
    "reported-by",
    "sponsored-by",
    "cc",
    "change-id",
];

/// Trailer keys (case-insensitive) that carry real intent and must be
/// preserved even when they sit between forbidden trailers.
const PRESERVED_TRAILER_KEYS: &[&str] = &[
    "closes",
    "close",
    "closed",
    "fix",
    "fixes",
    "fixed",
    "refs",
    "ref",
    "resolves",
    "resolve",
    "resolved",
    "see-also",
    "breaking change",
    "breaking-change",
    "deprecated",
];

/// Whole-line prefixes that identify AI-attribution banners that must be
/// dropped from the trailer block.
const AI_BANNER_PREFIXES: &[&str] = &[
    "🤖",
    "Generated with",
    "Generated by Claude",
    "Generated by ChatGPT",
    "Generated by GPT",
    "Co-Authored-By: Claude",
];

/// Sanitise an LLM-generated commit message.
///
/// Applies, in order:
/// `trim_blank_edges → collapse_blank_lines → strip_forbidden_trailers →
/// normalize_header_type_case → strip_subject_trailing_period →
/// trim_blank_edges`.
///
/// The function is idempotent: `sanitize(sanitize(x)) == sanitize(x)`.
pub fn sanitize_commit_message(text: &str) -> String {
    let s = trim_blank_edges(text);
    let s = collapse_blank_lines(&s);
    let s = strip_forbidden_trailers(&s);
    let s = normalize_header_type_case(&s);
    let s = strip_subject_trailing_period(&s);
    trim_blank_edges(&s)
}

/// Drop trailer-style lines that match the forbidden set, walking upward
/// from EOF over the tail trailer block.
///
/// Scanning stops at:
/// * the first blank line above the trailer block, or
/// * the first non-blank line that does not parse as a trailer at all
///   (i.e. is part of the body).
///
/// Lines whose trailer key is in [`PRESERVED_TRAILER_KEYS`] are kept and
/// scanning *continues* past them — this preserves `Closes #N` interleaved
/// with `Co-authored-by:` lines.
fn strip_forbidden_trailers(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').collect();
    if lines.is_empty() {
        return String::new();
    }

    let mut drop = vec![false; lines.len()];
    for i in (0..lines.len()).rev() {
        let trimmed = lines[i].trim();

        if trimmed.is_empty() {
            // Top of the trailing trailer block — stop scanning further up.
            break;
        }

        if is_ai_banner_line(trimmed) {
            drop[i] = true;
            continue;
        }

        match classify_trailer(trimmed) {
            TrailerClass::Forbidden => drop[i] = true,
            TrailerClass::Preserved => continue,
            TrailerClass::NotATrailer => break,
        }
    }

    let mut out = Vec::with_capacity(lines.len());
    for (i, line) in lines.iter().enumerate() {
        if !drop[i] {
            out.push(*line);
        }
    }
    out.join("\n")
}

#[derive(Debug, PartialEq, Eq)]
enum TrailerClass {
    Forbidden,
    Preserved,
    NotATrailer,
}

/// Classify a single non-blank line as a trailer.
///
/// Accepts both `Token: value` and `Token #value` (the git-trailers
/// convention used by `Closes #42`). The token may contain ASCII letters,
/// digits, dashes, and a single embedded space (so `BREAKING CHANGE` is
/// recognised).
fn classify_trailer(line: &str) -> TrailerClass {
    // Prefer the colon separator.
    if let Some(colon_pos) = line.find(':')
        && let Some(c) = classify_token(&line[..colon_pos])
    {
        return c;
    }
    // Fall back to ` #` (e.g. `Closes #42`).
    if let Some(hash_pos) = line.find(" #")
        && let Some(c) = classify_token(&line[..hash_pos])
    {
        return c;
    }
    TrailerClass::NotATrailer
}

fn classify_token(raw: &str) -> Option<TrailerClass> {
    let key = raw.trim();
    if key.is_empty() {
        return None;
    }
    if !key
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == ' ')
    {
        return None;
    }
    let key_lower = key.to_ascii_lowercase();
    if FORBIDDEN_TRAILER_KEYS.iter().any(|k| *k == key_lower) {
        return Some(TrailerClass::Forbidden);
    }
    if PRESERVED_TRAILER_KEYS.iter().any(|k| *k == key_lower) {
        return Some(TrailerClass::Preserved);
    }
    Some(TrailerClass::NotATrailer)
}

fn is_ai_banner_line(line: &str) -> bool {
    AI_BANNER_PREFIXES
        .iter()
        .any(|prefix| line.starts_with(prefix))
}

/// Lowercase the Conventional Commit type segment on the first line.
///
/// Header pattern recognised: `<type>(<scope>)?(!)?: <subject>`. Only
/// types in [`COMMIT_TYPES`] (matched case-insensitively) are normalised;
/// every other header passes through untouched.
fn normalize_header_type_case(text: &str) -> String {
    if let Some(nl) = text.find('\n') {
        let (first, rest) = text.split_at(nl);
        format!("{}{}", normalize_first_line(first), rest)
    } else {
        normalize_first_line(text)
    }
}

fn normalize_first_line(line: &str) -> String {
    let Some(colon_pos) = line.find(':') else {
        return line.to_string();
    };
    let head = &line[..colon_pos];
    let rest = &line[colon_pos..];

    let type_end = head.find(['(', '!']).unwrap_or(head.len());
    let type_part = &head[..type_end];
    let after_type = &head[type_end..];

    if type_part.is_empty() || !type_part.chars().all(|c| c.is_ascii_alphabetic()) {
        return line.to_string();
    }

    let type_lower = type_part.to_ascii_lowercase();
    if !COMMIT_TYPES.iter().any(|t| *t == type_lower) {
        return line.to_string();
    }

    format!("{}{}{}", type_lower, after_type, rest)
}

/// Remove a single trailing period from the subject line.
///
/// Preserves three-dot ellipsis (`...`), the unicode ellipsis (`…`), and
/// any other punctuation. Body lines are not touched.
fn strip_subject_trailing_period(text: &str) -> String {
    if let Some(nl) = text.find('\n') {
        let (first, rest) = text.split_at(nl);
        format!("{}{}", strip_first_line_period(first), rest)
    } else {
        strip_first_line_period(text)
    }
}

fn strip_first_line_period(line: &str) -> String {
    let trimmed = line.trim_end_matches(' ');
    if !trimmed.ends_with('.') || trimmed.ends_with("...") || trimmed.ends_with('…') {
        return line.to_string();
    }
    // Drop one trailing '.' and any whitespace that followed it.
    let without_period = &trimmed[..trimmed.len() - 1];
    without_period.trim_end_matches(' ').to_string()
}

/// Collapse runs of ≥ 2 blank lines down to a single blank line.
///
/// Lines inside a fenced code block (delimited by ```` ``` ```` or
/// `~~~` on a dedicated line) are passed through unchanged so embedded
/// blank lines remain semantic.
fn collapse_blank_lines(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut out: Vec<&str> = Vec::with_capacity(lines.len());
    let mut last_blank = false;
    let mut in_fence = false;

    for line in &lines {
        let trimmed = line.trim();

        // Fence delimiters toggle in_fence and always pass through.
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            in_fence = !in_fence;
            last_blank = false;
            out.push(*line);
            continue;
        }

        if in_fence {
            last_blank = false;
            out.push(*line);
            continue;
        }

        if trimmed.is_empty() {
            if last_blank {
                continue;
            }
            last_blank = true;
            out.push(*line);
        } else {
            last_blank = false;
            out.push(*line);
        }
    }

    out.join("\n")
}

/// Drop blank lines at the very top and very bottom of the message.
/// Internal blank separators are preserved.
fn trim_blank_edges(text: &str) -> String {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut start = 0;
    while start < lines.len() && lines[start].trim().is_empty() {
        start += 1;
    }
    let mut end = lines.len();
    while end > start && lines[end - 1].trim().is_empty() {
        end -= 1;
    }
    lines[start..end].join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    // ============================== strip_forbidden_trailers ==============================

    #[test]
    fn strip_forbidden_drops_coauthored_by() {
        let input = "feat: x\n\nCo-authored-by: Alice <alice@example.com>";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_drops_multiple_coauthored() {
        let input = "feat: x\n\nCo-authored-by: A <a@b>\nCo-authored-by: B <b@c>";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_drops_signed_off_by() {
        let input = "feat: x\n\nSigned-off-by: A <a@b>";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_preserves_closes_between_forbidden() {
        let input = "feat: x\n\nCloses #1\nCo-authored-by: A <a@b>\nRefs #2";
        // Both forbidden interleaved are dropped; Closes and Refs preserved.
        assert_eq!(
            strip_forbidden_trailers(input),
            "feat: x\n\nCloses #1\nRefs #2"
        );
    }

    #[test]
    fn strip_forbidden_preserves_fixes_alone() {
        let input = "feat: x\n\nFixes #42";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n\nFixes #42");
    }

    #[test]
    fn strip_forbidden_preserves_breaking_change() {
        let input = "feat!: x\n\nBREAKING CHANGE: api removed";
        assert_eq!(
            strip_forbidden_trailers(input),
            "feat!: x\n\nBREAKING CHANGE: api removed"
        );
    }

    #[test]
    fn strip_forbidden_case_insensitive() {
        let input = "feat: x\n\nco-AUTHORED-by: A <a@b>";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_drops_change_id() {
        let input = "feat: x\n\nChange-Id: Iabc123";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_drops_ai_banner() {
        let input = "feat: x\n\n🤖 Generated with [Claude Code]";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_drops_generated_with() {
        let input = "feat: x\n\nGenerated with Claude Sonnet 4.5";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n");
    }

    #[test]
    fn strip_forbidden_preserves_body_mention() {
        // The phrase "co-authored-by" appears inside a body paragraph, not as
        // a trailer line. Scanning must stop at the body and leave it intact.
        let input =
            "feat: x\n\nThis body mentions co-authored-by inside prose but is not a trailer.";
        assert_eq!(strip_forbidden_trailers(input), input);
    }

    #[test]
    fn strip_forbidden_empty_input() {
        assert_eq!(strip_forbidden_trailers(""), "");
    }

    #[test]
    fn strip_forbidden_no_trailer_block() {
        let input = "feat: just a subject, no body, no trailers";
        assert_eq!(strip_forbidden_trailers(input), input);
    }

    #[test]
    fn strip_forbidden_with_hash_separator() {
        // Closes #N uses the ` #` separator, not `:`. Must still be preserved.
        let input = "feat: x\n\nCloses #1\nCo-authored-by: A <a@b>";
        assert_eq!(strip_forbidden_trailers(input), "feat: x\n\nCloses #1");
    }

    // ============================== normalize_header_type_case ==============================

    #[test]
    fn normalize_lowercases_type() {
        assert_eq!(normalize_header_type_case("Feat: x"), "feat: x");
    }

    #[test]
    fn normalize_with_scope() {
        assert_eq!(normalize_header_type_case("FIX(api): y"), "fix(api): y");
    }

    #[test]
    fn normalize_with_bang() {
        assert_eq!(
            normalize_header_type_case("Feat!: breaking"),
            "feat!: breaking"
        );
    }

    #[test]
    fn normalize_with_scope_and_bang() {
        assert_eq!(
            normalize_header_type_case("Chore(deps)!: bump"),
            "chore(deps)!: bump"
        );
    }

    #[test]
    fn normalize_passes_through_unknown_type() {
        // "Update" is not in the whitelist; leave untouched.
        assert_eq!(normalize_header_type_case("Update: x"), "Update: x");
    }

    #[test]
    fn normalize_passes_through_no_colon() {
        assert_eq!(
            normalize_header_type_case("Add new login form"),
            "Add new login form"
        );
    }

    #[test]
    fn normalize_only_touches_first_line() {
        let input = "Feat: x\n\nFix something else in body: details";
        assert_eq!(
            normalize_header_type_case(input),
            "feat: x\n\nFix something else in body: details"
        );
    }

    #[test]
    fn normalize_preserves_scope_case() {
        // We only lowercase the type token. Scope is left untouched.
        assert_eq!(normalize_header_type_case("FEAT(API): x"), "feat(API): x");
    }

    #[test]
    fn normalize_subject_with_colons() {
        assert_eq!(
            normalize_header_type_case("Feat: add a:b mapping"),
            "feat: add a:b mapping"
        );
    }

    #[test]
    fn normalize_empty_input() {
        assert_eq!(normalize_header_type_case(""), "");
    }

    #[test]
    fn normalize_already_lowercase() {
        assert_eq!(normalize_header_type_case("feat(api): x"), "feat(api): x");
    }

    // ============================== strip_subject_trailing_period ==============================

    #[test]
    fn strip_period_single() {
        assert_eq!(strip_subject_trailing_period("feat: x."), "feat: x");
    }

    #[test]
    fn strip_period_preserves_ellipsis_dots() {
        assert_eq!(strip_subject_trailing_period("feat: x..."), "feat: x...");
    }

    #[test]
    fn strip_period_preserves_unicode_ellipsis() {
        assert_eq!(strip_subject_trailing_period("feat: x…"), "feat: x…");
    }

    #[test]
    fn strip_period_preserves_exclaim() {
        assert_eq!(strip_subject_trailing_period("feat: x!"), "feat: x!");
    }

    #[test]
    fn strip_period_preserves_question() {
        assert_eq!(strip_subject_trailing_period("feat: x?"), "feat: x?");
    }

    #[test]
    fn strip_period_preserves_inner_dots() {
        assert_eq!(
            strip_subject_trailing_period("feat: handle 3.14 in parser."),
            "feat: handle 3.14 in parser"
        );
    }

    #[test]
    fn strip_period_only_touches_first_line() {
        let input = "feat: x.\n\nBody line ends with a period.";
        assert_eq!(
            strip_subject_trailing_period(input),
            "feat: x\n\nBody line ends with a period."
        );
    }

    #[test]
    fn strip_period_with_trailing_whitespace() {
        assert_eq!(strip_subject_trailing_period("feat: x.   "), "feat: x");
    }

    #[test]
    fn strip_period_idempotent_on_no_period() {
        assert_eq!(strip_subject_trailing_period("feat: x"), "feat: x");
    }

    #[test]
    fn strip_period_empty() {
        assert_eq!(strip_subject_trailing_period(""), "");
    }

    // ============================== collapse_blank_lines ==============================

    #[test]
    fn collapse_three_blank_into_one() {
        let input = "a\n\n\n\nb";
        assert_eq!(collapse_blank_lines(input), "a\n\nb");
    }

    #[test]
    fn collapse_single_blank_unchanged() {
        let input = "a\n\nb";
        assert_eq!(collapse_blank_lines(input), "a\n\nb");
    }

    #[test]
    fn collapse_no_blanks() {
        let input = "a\nb\nc";
        assert_eq!(collapse_blank_lines(input), "a\nb\nc");
    }

    #[test]
    fn collapse_preserves_fenced_blanks() {
        // Inside ``` … ``` we leave blank lines alone (they may be code).
        let input = "a\n\n```\n\n\n\n```\n\nb";
        assert_eq!(collapse_blank_lines(input), "a\n\n```\n\n\n\n```\n\nb");
    }

    #[test]
    fn collapse_empty_input() {
        assert_eq!(collapse_blank_lines(""), "");
    }

    #[test]
    fn collapse_only_blanks() {
        let input = "\n\n\n";
        // 4 blank "lines" → one blank line emitted, others dropped.
        assert_eq!(collapse_blank_lines(input), "");
    }

    #[test]
    fn collapse_tilde_fence_treated_as_fence() {
        let input = "a\n\n~~~\n\n\n~~~\n\nb";
        assert_eq!(collapse_blank_lines(input), "a\n\n~~~\n\n\n~~~\n\nb");
    }

    #[test]
    fn collapse_two_paragraphs_three_blanks() {
        let input = "title\n\n\n\nbody continues here";
        assert_eq!(collapse_blank_lines(input), "title\n\nbody continues here");
    }

    #[test]
    fn collapse_trailing_blanks() {
        let input = "a\n\n\n\n";
        assert_eq!(collapse_blank_lines(input), "a\n");
    }

    #[test]
    fn collapse_leading_blanks() {
        let input = "\n\n\na";
        assert_eq!(collapse_blank_lines(input), "\na");
    }

    // ============================== trim_blank_edges ==============================

    #[test]
    fn trim_edges_leading_only() {
        assert_eq!(trim_blank_edges("\n\nfoo"), "foo");
    }

    #[test]
    fn trim_edges_trailing_only() {
        assert_eq!(trim_blank_edges("foo\n\n"), "foo");
    }

    #[test]
    fn trim_edges_both() {
        assert_eq!(trim_blank_edges("\n\nfoo\n\n"), "foo");
    }

    #[test]
    fn trim_edges_no_blank() {
        assert_eq!(trim_blank_edges("foo\nbar"), "foo\nbar");
    }

    #[test]
    fn trim_edges_preserves_internal() {
        assert_eq!(trim_blank_edges("foo\n\nbar"), "foo\n\nbar");
    }

    #[test]
    fn trim_edges_all_blank() {
        assert_eq!(trim_blank_edges("\n\n\n"), "");
    }

    #[test]
    fn trim_edges_empty() {
        assert_eq!(trim_blank_edges(""), "");
    }

    #[test]
    fn trim_edges_whitespace_only_lines() {
        assert_eq!(trim_blank_edges("   \n\t\nfoo\n   "), "foo");
    }

    // ============================== sanitize_commit_message (end-to-end) ==============================

    #[test]
    fn sanitize_well_formed_passthrough() {
        let input = "fix(auth): reject expired refresh tokens\n\n\
                     Return 401 when a refresh token is expired instead of issuing\n\
                     a new access token.\n\n\
                     Fixes #128";
        assert_eq!(sanitize_commit_message(input), input);
    }

    #[test]
    fn sanitize_strips_capitalised_type_and_period() {
        let input = "Feat(api): add token rotation.";
        assert_eq!(
            sanitize_commit_message(input),
            "feat(api): add token rotation"
        );
    }

    #[test]
    fn sanitize_drops_ai_signature() {
        let input = "feat: x\n\nCloses #1\n\n🤖 Generated with [Claude Code]\nCo-authored-by: Claude <noreply@anthropic.com>";
        let out = sanitize_commit_message(input);
        assert!(!out.contains("Co-authored-by"));
        assert!(!out.contains("🤖"));
        assert!(out.contains("Closes #1"));
    }

    #[test]
    fn sanitize_collapses_blank_runs() {
        let input = "feat: x\n\n\n\nbody here\n\n\n";
        assert_eq!(sanitize_commit_message(input), "feat: x\n\nbody here");
    }

    #[test]
    fn sanitize_idempotent() {
        let raw = "FEAT(API)!: drop legacy endpoint.\n\n\
                   This breaks public callers.\n\n\
                   BREAKING CHANGE: API removed\n\
                   Co-authored-by: Alice <alice@example.com>\n\
                   Closes #42";
        let once = sanitize_commit_message(raw);
        let twice = sanitize_commit_message(&once);
        assert_eq!(once, twice);
    }

    #[test]
    fn sanitize_preserves_breaking_change_pair() {
        let input = "Feat!: drop legacy api\n\nBREAKING CHANGE: api removed";
        assert_eq!(
            sanitize_commit_message(input),
            "feat!: drop legacy api\n\nBREAKING CHANGE: api removed"
        );
    }

    #[test]
    fn sanitize_handles_empty() {
        assert_eq!(sanitize_commit_message(""), "");
    }

    #[test]
    fn sanitize_complex_real_world() {
        let raw = "\n\n\
                   Feat(payment): add retry logic.\n\n\
                   Add `retry()` helper to recover from transient gateway errors.\n\
                   Previously a single 502 would propagate to the user.\n\n\
                   Closes #128\n\
                   Co-authored-by: Bot <bot@example.com>\n\
                   Signed-off-by: Bot <bot@example.com>\n\
                   🤖 Generated with [Claude Code]\n\n";
        let out = sanitize_commit_message(raw);
        assert!(out.starts_with("feat(payment): add retry logic\n\n"));
        assert!(out.contains("Closes #128"));
        assert!(!out.contains("Co-authored-by"));
        assert!(!out.contains("Signed-off-by"));
        assert!(!out.contains("🤖"));
        assert!(!out.ends_with('\n'));
    }
}
